logging enhancement
fmeringdal/nettu-meet pull request #32
Opened 2021-08-02 15:33 UTC by YuTaeseong

#2 logging enhancement.

frontend

In Chrome Browser
![image](https://user-images.githubusercontent.com/16485416/127886661-7da15057-b18d-4044-ac22-be3c94d2db0f.png)

server

In terminal
![image](https://user-images.githubusercontent.com/16485416/127886393-68834a51-9cea-4b6f-aaf4-0ffeaec5c1cd.png)

In Kibana
![image](https://user-images.githubusercontent.com/16485416/127886574-6ab9d9e0-3f82-4fd8-a7e6-5eada56f162c.png)

Let me know if you want more enhancement

2021-08-04 18:08 UTC, fmeringdal requested changes
Hi @YuTaeseong ,

Thanks for your PR. It looks good, but just needs a couple of changes before it can be approved :)

2021-08-04 18:08 UTC, fmeringdal commented on server/src/config/index.ts
> +const elasticsearchURL = process.env['NETTU_Elastic_URL'];
Please change `NETTU_Elastic_URL` to `NETTU_ELASTIC_URL`

2021-08-04 18:08 UTC, fmeringdal commented on server/src/logger.ts
> +const streamToElastic = pinoElastic({
Only add `streamToElastic` if `elasticsearchURL` is not null. If `elasticsearchURL` is null then stream to stdout even if in production

2021-08-05 03:02 UTC, YuTaeseong commented
> Hi @YuTaeseong ,
> 
> Thanks for your PR. It looks good, but just needs a couple of changes before it can be approved :)

I've done your request!!

2021-08-08 20:07 UTC, fmeringdal approved these changes
Looks good!

2021-08-08 20:07 UTC, merged